### ISSUE TITLE
Duplicated entries in content suggestions 

### ISSUE THREAD

**Issue by iantmoore** [G2G3Digital/substeps-eclipse-plugin#30]
raised via google groups

eg: 
ClickButton <buttonText>
ClickButton <value>

doesn't appear to affect substep definitions, just step impls in jars

![substeps-eclipse-auto-complete](https://f.cloud.github.com/assets/1705914/134954/24cd63fa-7105-11e2-9074-ef1e34900a00.png)

**Comment by stuforbes** [comment]
This issue appears to have been fixed with the new changes to the substeps-core/api within the core bundle
